### ISSUE TITLE
Mamute development on linux

### ISSUE THREAD

**Issue by code4passion** [caelum/mamute#125]
Looking at the readme, it seems that MAMUTE has been written to work on linux. Can it be run on windows? Where can I find the steps on how to do it?

**Comment by roanosullivan** [comment]
I was able to run mamute on Windows 7 in a Cygwin terminal with the following run.sh script:

```
#!/bin/bash

TIMESTAMP=20150302170820
MAMUTE_DIR=`cygpath -w -a .`
CP_LIST="`cygpath -w -a WEB-INF/classes/`;`cygpath -w -a WEB-INF/lib/* | tr '\\n' ';'`"

echo $CP_LIST
echo $MAMUTE_DIR

java -cp $CP_LIST \
    -Ddeploy.timestamp=$TIMESTAMP \
    -Dvraptor.webappdir=${MAMUTE_DIR} \
    -Dserver.port=8080\
    ${MAMUTE_OPTS} \
    br.com.caelum.vraptor.server.Main \
    not-grunt

```

Also beware: for me the mamute build (scripts/mvn-package.sh) appeared to succeed on Windows+Cygwin, but then I discovered that CSS and JS fail to load when I browsed to home page. The issue was usemin had not replaced minified filenames with rev'd filenames in .tag and .jspf files. After modifying Gruntfile.js to get usemin and filerev to work correctly with Windows paths, everything seems to work. 

For good measure I also ran ```find src/main/webapp/ -type f -exec unix2dos {} \;``` before building mamute on Windows+Cygwin.

**Comment by leocwolter** [comment]
Hi @roanosullivan, do you mind to open a PR for us with your modifications? It would be great!
