### ISSUE TITLE
When trying to update user profile with empty "about" page, exception is thrown and not handled

### ISSUE THREAD

**Issue by MatejBalantic** [caelum/mamute#130]
Steps to reproduce:

1. Log in with connected user (FB, Google) which has an empty about field
2. Go to profile editing
3. Submit

Expected results: 
User would be notified that he needs to provide an about page, or, even better, about page would already be enforced on registration. 

Actual results:
br.com.caelum.vraptor.validator.validationexception  exception is thrown, no reason given

There are two problems here as I see it:
* the issue should have been caught before user is allowed to submit the form
* in case he manages to still submit the form, gracefull error reporting should be done

**Comment by csokol** [comment]
I found that this interceptor is causing this issue: https://github.com/caelum/mamute/blob/master/src/main/java/org/mamute/interceptors/ConversionErrorsInterceptor.java

When I remove it, the validations errors are handled as usual. I'm not sure why this interceptor even exists, any ideas, @leocwolter?

Anyway, since the user can create his account without providing all this info, he should be able to edit it as well... So I guess that the "About you" field should be optional. What do you think?

**Comment by leocwolter** [comment]
Maybe at the time we implemented this VRaptor wasn't handling conversion errors. If it works will without it feel free to remove :)

**Comment by MatejBalantic** [comment]
Fixed with https://github.com/caelum/mamute/pull/136
