### ISSUE TITLE
How do I attach a debugger to this process?

### ISSUE THREAD

**Issue by ot-brian-mackey** [caelum/mamute#148]
How do I attach a debugger to Mamute so I can troubleshoot possible runtime errors?  After launching netbeans with "gksu /usr/bin/netbeans", I go to top menu > Debugger > Attach Debugger > 

- Java Debugger (JPDA) 
- Process Attach (by pid)
- Transport = local
- PID = XXXX (XXXX obtained by running "lsof -i :8080)

Click Attach.  Error: 

> Not a debuggee or not listening for a debugger to attach.  

I'm running Debian.

**Comment by MatejBalantic** [comment]
I usually just run the project from IntelliJ and get this for free.

**Comment by csokol** [comment]
What command did you used to run mamute, @ot-brian-mackey?

**Comment by monitorjbl** [comment]
I don't bother with PID attachment, I just use remote debugging. You add this to the running configuration of the application 

```
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6000
```

and then you use your IDE's remote debug connection to attach to the host. You can use this locally or remotely.

**Comment by xdarklight** [comment]
Running the project from eclipse used to work fine by running ```br.com.caelum.vraptor.server.Main.main(String[])```
However, since 2dddd8efec702ca36c950211287cb144a7038c43 vraptor-test is also in the classpath when starting Mamute from eclipse, which causes everything to break.

My workaround for this:
* right-click on the Mamute project
* Preferences -> Java Build Path -> Libraries tab
* Search for "M2_REPO/br/com/caelum/vraptor/vraptor-test/4.0.0/vraptor-test-4.0.0.jar" and remove it

**Comment by felipeweb** [comment]
i'm closing here feel free to reopen, if you want
