### ISSUE TITLE
Mamute doesn't permit Unicode character in URL

### ISSUE THREAD

**Issue by khajavi** [caelum/mamute#214]
I'm localizing mamute in Persian language. There is a problem with creating new questions that are written in Persian. Mamute doesn't create long URL for these questions.

![shomabegoo](https://cloud.githubusercontent.com/assets/235974/12074907/68d11422-b183-11e5-98d6-25175462dbb5.png)

Which class I need to change to fix this problem?

**Comment by JamesSullivan** [comment]
The problem is in src/main/java/org/mamute/infra/NormalizerBrutal.java where non-latin characters are being purposefully discarded

`String slug = NONLATIN.matcher(normalized).replaceAll("");`

There is actually no need for this. If you use the code from pull request #135 with the NormalizerBrutal.java file I have included in the comments for the same pull request you can use Unicode in the URLs for questions.

**Comment by khajavi** [comment]
thank you @JamesSullivan
